services:
  - type: web
    name: chatbothealth
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true
    plan: free
